server:
  port: 8082

spring:
  application:
    name: user-management

emailQueueName: send-email

uaa:
  url: http://localhost:8080
  createUserClient:
    id: login
    secret: loginsecret
  loginUserClient:
      id: app
      secret: appclientsecret

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
